POST http://localhost:3000/api/skill
Content-Type: application/json

{
    "name": "CSS"
}

###

GET http://localhost:5000/api/skill

###

PUT http://localhost:3000/api/skill/1
Content-Type: application/json

{
    "name": "Express.js"
}

###

DELETE http://localhost:3000/api/skill/1